[tool.black]
line-length = 88  # Standard recommended line length for Black
target-version = ["py310", "py311", "py312"]  # Target Python versions used in development/CI
exclude = "(build|dist|\\.venv)"  # Exclude virtualenv and build folders

[tool.ruff]
line-length = 88  # Keep consistent with Black
exclude = ["build", "dist", ".venv"]  # Exclude common non-source folders

[tool.ruff.lint]
select = ["E", "F", "B", "W", "I"]  
# E = pycodestyle (style issues)
# F = pyflakes (code errors)
# B = bugbear (common mistakes & best practices)
# W = warnings
# I = isort rules (import sorting)

ignore = ["E501"]  
# E501 = line too long → ignored because Black handles line wrapping
