name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    name: Ruff Linter
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install ruff

      - name: Run Ruff
        run: |
          ruff check .

  black-format:
    runs-on: ubuntu-latest
    name: Black Code Formatter Check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install black

      - name: Run Black (Check Only)
        run: |
          black --check .
